### ISSUE TITLE
Pass e-mail address to letsencrypt from plugin

### ISSUE THREAD

**Issue by sseemayer** [sseemayer/dokku-letsencrypt#15]
Since it is important that the `letsencrypt` command can be run from cron (i.e. no TTY), it is important that we're able to run the letsencrypt docker container without a TTY attached.

On first run of the plugin, the container will currently ask for the user's e-mail address to register a new account. In some configurations (ref. #14), the current terminal detection methods fail and the docker container crashes with the `PythonDialogBug` error.

Add a `letsencrypt:register` command that can be performed once to create a user account with let's encrypt and to ensure that future interactions with the docker container can run fully automated.

**Comment by sseemayer** [comment]
Cross-post from #14, here is how to specify an e-mail address to the letsencrypt container:

```
  -m EMAIL, --email EMAIL
                        Email used for registration and recovery contact.
                        (default: None)
```

**Comment by sseemayer** [comment]
As far as I currently understand the let's encrypt state machine / workflow, the e-mail address will be used only if no account is found in `/etc/letsencrypt/accounts` to request a new account with that e-mail address. I'm not sure if specifying an e-mail address on subsequent validation or signing requests will have any effect, though and this will have to be checked.

**Comment by sseemayer** [comment]
Since there was also a request for [separate e-mail addresses for different apps](https://github.com/sseemayer/dokku-letsencrypt/issues/14#issuecomment-168687289), there would probably have to be separate accounts for separate e-mail adresses. Since this would considerably complicate the plugin and possibly user interface, how much of a demand for this is there? @fruitl00p , would you be interested in contributing a patch for this?

**Comment by fruitl00p** [comment]
@sseemayer It seems to me that moving from host-wide credentials to per-app credentials would be achievable by chaning the mountpoint for .letsencrypt ?

I'd say doing something like the following around [here](https://github.com/sseemayer/dokku-letsencrypt/blob/master/commands#L19):
```
[[ -d "$APP_ROOT/.letsencrypt" ]] && LETSENCRYPT_ROOT="$APP_ROOT/.letsencrypt" || LETSENCRYPT_ROOT="$DOKKU_ROOT/.letsencrypt"
```

Then additionally the ```:register``` action could optionally have the ```<app>``` passed and only that would have to handle the ```$APP_ROOT``` / ```$DOKKU_ROOT```

* this is an untested top of my head hack *
but the idea should be workable ;)

**Comment by sseemayer** [comment]
I'm working on this now using a key storage strategy similar to your proposal. The change will come together with a change to https://github.com/kuba/simp_le instead of the official client since it's much easier to automate that client (no user prompts ftw!)

**Comment by fruitl00p** [comment]
:+1: cool! Looking forward to it!
